"""
Django settings for optimal_route_finder project.

Generated by 'django-admin startproject' using Django 1.10.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

ALLOWED_HOSTS = ['*']

from optimal_route_finder import PROJECT_BASE_DIR

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = PROJECT_BASE_DIR

# Application definition

INSTALLED_APPS = [
    'rest_framework',
    # 'grids'
]

REST_FRAMEWORK = {
    'UNAUTHENTICATED_USER': None
}

# MIDDLEWARE = [
#     'optimal_route_finder.middlewares.handle_exception.HandleExceptionMiddleware',
# ]

ROOT_URLCONF = 'optimal_route_finder.urls'

WSGI_APPLICATION = 'optimal_route_finder.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases


DATABASE_SETTINGS = {
    'mongodb': {
        'NAME': os.environ.get('TEST_MONGO_DB_NAME', 'grid_test'),
        'USER': os.environ.get('TEST_MONGO_DB_USER'),
        'PASS': os.environ.get('TEST_MONGO_DB_PASSWORD'),
        'HOST': os.environ.get('TEST_MONGO_DB_HOST', 'localhost'),
        'PORT': os.environ.get('TEST_MONGO_DB_PORT', '27017'),
    },
}

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.environ.get('TIMEZONE', 'UTC')

USE_I18N = True

USE_L10N = True

USE_TZ = True

